function run_iasi_compress()
addpath(genpath('~/git/rtp_prod2'));
addpath('~/git/iasi_pcc');

% grab the slurm array index for this process
slurmindex = str2num(getenv('SLURM_ARRAY_TASK_ID'));

% File ~/cris-files-process.txt is a list of filepaths to the input
% files or this processing. For the initial runs, this was
% generated by a call to 'ls' while sitting in the directory
% /asl/data/cris/ccast/sdr60_hr/2015: 
%    ls -d1 $PWD/{048,049,050}/*.mat >> ~/cris-files-process.txt
%
% cris-files-process.txt, then, contains lines like:
%    /asl/data/cris/ccast/sdr60_hr/2015/048/SDR_d20150217_t1126169.mat
[status, infile] = system(sprintf('sed -n "%dp" %s | tr -d "\n"', ...
                                  slurmindex, '~/git/iasi_pcc/iasi_file_list'));

% separate out parts of file path. We want to keep the bulk of the
% filename intact but change SDR -> rtp and change the extension to
% rtp as well as we make the output file path
IASI_DIR = '/asl/data/IASI';
IASI_PCC_DIR = fullfile(IASI_DIR, 'PCC');
[pathstr, name, ext] = fileparts(infile);
outfile = fullfile(IASI_PCC_DIR, [name, '.pcc']);

% call the processing function
iasi_pcc_compress_granule(infile, outfile)

end